spring.application.name=progetto-scuola
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/didattica
spring.datasource.username=didattica_user
spring.datasource.password=didattica_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=didattica

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=900000
app.auth.cookie-name=auth_token
app.auth.cookie-secure=false
app.auth.cookie-same-site=Lax
app.auth.cookie-path=/
app.auth.cookie-max-age=86400