spring.application.name=progetto-scuola
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/didattica
spring.datasource.username=didattica_user
spring.datasource.password=didattica_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=didattica